schema_version = "1.0.0"

id = "select_by_constraint_rknz"
name = "Select By Constraint RKNZ"
version = "1.0.0"
tagline = "Select bones by constraint type in Pose Mode"
maintainer = "Rikokenz <https://github.com/rikokenz>"
type = "add-on"
website = "https://github.com/rikokenz/Select-Bone-By-Constraint-RKNZ"

tags = ["Animation"]

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]
